[project]
name = "fftsqueeze"
version = "0.1.0"
description = "C++ MATLAB-generated code for FSST"
authors = ["Alvaro <alvgaona@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
opencv = ">=4.10.0,<5"

[feature.build.dependencies]
cmake = ">=3.30.5,<4"
make = ">=4.4.1,<5"
ninja = ">=1.12.1,<2"
cxx-compiler = ">=1.8.0,<2"

[feature.build.tasks.configure]
cmd = ["cmake", "-GNinja", "-S.", "-Bbuild"]
inputs = ["CMakeLists.txt"]
outputs = ["build/CMakeFiles/"]

[feature.build.tasks.build]
cmd = ["cmake", "--build", "build"]
depends-on = ["configure"]
inputs = ["CMakeLists.txt", "src/*"]
outputs = ["build/bin/some"]

[environments]
build = ["build"]
